version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=kuna1234
      - POSTGRES_DB=stori-candidate
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8282:8282"
    environment:
      - DB_SOURCE=postgresql://root:kuna1234@postgres:5432/stori-candidate?sslmode=disable
    depends_on:
      - postgres
    # wait-for.sh helps to wait until postres service is available to interact with it
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
volumes:
  data-volume: