// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Account struct {
	ID         int64     `json:"id"`
	Owner      string    `json:"owner"`
	CardNumber string    `json:"card_number"`
	CreatedAt  time.Time `json:"created_at"`
}

type Transaction struct {
	ID        int64  `json:"id"`
	AccountID int64  `json:"account_id"`
	Date      string `json:"date"`
	// can be negative ( - Debit) or possitive ( + Credit)
	Transaction float64 `json:"transaction"`
}
